use_frameworks! :linkage => :static

platform :ios, '14.0'

target 'HexaPlayer_Example' do
  pod 'HexaPlayer', :path => '../'

  target 'HexaPlayer_Tests' do
    inherit! :search_paths

    
  end
end
